//Check if the given number is armstrong or not 

#include <stdio.h>
#include <math.h>

int Cal_Armstrong (int x, int y){

	if(x > 0)
		return (pow(x%10,y) + Cal_Armstrong(x/10,y)); //recursion used to calculate the sum and power for each digit
	else 
		return 0;
}

int main() {
	int num, temp, n=0;

	printf("Enter the number to check if armstrong or not: ");
	scanf("%d", &num); // taking input 

	temp = num;

	while(temp !=0){ // calculating the number of digits
		temp /= 10;
		n++;
	}

	if(Cal_Armstrong(num, n) == num) // checking if the sum of powers of digit generated by the function is equal to the number itself
		printf("Given number %d is armstrong!!\n", num);
	else
		printf("Given number %d is not armstrong!!\n", num);
	
	return 0;
}
